using System.ComponentModel.DataAnnotations;


namespace ALectureManager.Encoder;

public partial class EncoderProcessData : ObservableObject
{
    [Key] public Guid Id { get; set; } = Guid.NewGuid();

    #region AvaloniaAutoGeneratedProps
    [ObservableProperty] private string _name = string.Empty;
    [ObservableProperty] private string _inputPath = string.Empty;
    [ObservableProperty] private string _outputPath = string.Empty;
    [ObservableProperty] private long _progressBarMax = 100;
    [ObservableProperty] private long _progressBarValue;

    [ObservableProperty] private long _resumeFrame = 0;
    [ObservableProperty] private long _totalFrames = 0;
    [ObservableProperty] private string _status = string.Empty;

    [ObservableProperty] private long _frame = 0;
    [ObservableProperty] private float _fps = 0;
    [ObservableProperty] private TimeSpan _time = TimeSpan.Zero;
    
    // not really using this one but maybe in future i willl want to display it too
    [ObservableProperty] private string _bitrate = string.Empty;
    [ObservableProperty] private float _speed = 0;
    [ObservableProperty] private bool _started;
    [ObservableProperty] private bool _paused;

    [ObservableProperty] private bool _finished;

    [ObservableProperty] private CodecOption? _codecOption;

    #endregion
}

